name: Verify Package Sync

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Verify package sync
        run: |
          npm install --package-lock-only
          git diff --exit-code package-lock.json || \
          (echo "package.json and package-lock.json are out of sync" && exit 1)
